### PR TITLE
PVC fill up scenario improvement

### PR DESCRIPTION
**Pull request by agullon**
Adding new function to remove temp file in case of failure

### CODE REVIEW

**Comment by agullon** [comment]
Hi @chaitanyaenr @yogananth-subramanian pinging you because I can not add you as reviewers of this PR.

**Review by yogananth-subramanian — APPROVED** [review]
LGTM!

**Review by chaitanyaenr — APPROVED** [review]
LGTM!

**Comment by agullon** [comment]
@chaitanyaenr @yogananth-subramanian can we merge it now?

**Pull request merged**
